palladians/pallad

- apps/website/src/components/Features.astro
- apps/website/src/components/HeroSection.astro
This pull request introduces changes to the copy on the home page, specifically within the Hero and Feature sections. The updates aim to make the content more engaging and informative, providing clear and concise information about Pallad's feature set. This should help to increase user understanding and boost conversion rates.
> Revamp Home Page: Enhance Hero & Feature Section Copy

- packages/features/.ladle/utils.ts
incorrect package used `mina`, updated to use `key-generator`
> fix: fixed incorrect import

- .dokku-monorepo
- packages/features/package.json
- packages/features/src/Router.tsx
- packages/features/src/common/components/BottomNavigation.tsx
- packages/features/src/lock/views/UnlockWallet.tsx
- packages/features/src/send/components/TransactionResult.tsx
- packages/features/src/send/views/TransactionError.stories.tsx
- packages/features/src/send/views/TransactionSuccess.stories.tsx
- packages/features/src/staking/components/EpochProgressChart.tsx
- packages/features/src/staking/views/StakingOverview.stories.tsx
- packages/features/src/staking/views/StakingOverview.tsx
- packages/features/src/transactions/views/TransactionDetails.stories.tsx
- packages/features/src/transactions/views/Transactions.stories.tsx
- packages/ui/src/components/Box/index.css.ts
- yarn.lock
> fix(staking): add mocked overview

- packages/features/src/Router.tsx
- packages/features/src/about/views/About.tsx
- packages/features/src/common/lib/numbers.ts
- packages/features/src/staking/components/BlockProducerTile.tsx
- packages/features/src/staking/views/BlockProducers.stories.tsx
- packages/features/src/staking/views/BlockProducers.tsx
- packages/features/src/staking/views/Delegate.stories.tsx
- packages/features/src/staking/views/Delegate.tsx
- packages/features/src/staking/views/StakingOverview.stories.tsx
- packages/features/src/staking/views/StakingOverview.tsx
- packages/ui/src/components/Avatar/index.stories.tsx
- packages/ui/src/components/Avatar/index.tsx
- packages/ui/src/index.ts
> feat(staking): add mocked delegate view

- packages/mina-graphql/test/Providers/TxSubmitProvider.test.ts
- packages/mina-wallet/README.md
- packages/mina-wallet/src/Wallet/Wallet.ts
- packages/mina-wallet/src/types.ts
- packages/mina-wallet/test/Wallet.test.ts
In this pull request, we have added significant functionality to the MinaWallet.
- In `TxSubmitProvider.test.ts`, we have added the use of `constructTransaction` function before signing the transactions. This new functionality ensures that the transaction is properly built before being signed.
- In `Wallet.ts`, `MinaWalletImpl` has been expanded to include a `TxSubmitGraphQLProvider` instance. This will provide the capability to submit transactions. Additionally, we uncommented and implemented the `submitTx` method, which allows the submission of a transaction to the network. We still have a TODO item to verify the transaction before returning it and adding a pending transaction to the pending transaction store that checks for transaction status at an interval.
- In `types.ts`, we updated …
> Enhancements to `@palladxyz/mina-wallet`: Adding Construct and Submit Transaction Functionality

- apps/website/package.json
- apps/website/src/components/AppFooter.astro
- apps/website/src/components/AppHeader.astro
- apps/website/src/components/CallToAction.astro
- apps/website/src/components/Features.astro
- apps/website/src/components/HeroSection.astro
- apps/website/src/components/Stats.astro
- apps/website/src/layouts/Layout.astro
- apps/website/src/pages/index.astro
- yarn.lock
- Update website mocked contents.
-
> feat(website): wrap up the landing page

- packages/vault/src/stores.ts
- packages/vault/src/types.ts
- packages/vault/src/vault.ts
- packages/vault/test/stores.test.ts
Adding wallet restoration behaviour to the store's methods.
- `addCredential()`
> Add wallet restoration behaviour to the store's methods

- packages/mina-wallet/src/Wallet/Wallet.ts
- packages/mina-wallet/src/types.ts
- packages/mina-wallet/test/Wallet.test.ts
Update wallet to use new `restoreWallet` network args
> Update wallet to use new `restoreWallet` network args

- packages/key-mangement/package.json
- packages/key-mangement/src/emip3.ts
- packages/key-mangement/test/InMemoryKeyAgent.test.ts
- yarn.lock
Refactor: Use `@noble/ciphers` - goal is to remove `chacha-js` dependency.
> Refactor: Use `@noble/ciphers`

- README.md
- Added automatic contributors avatars.
- Updated descriptions and package list in Readme.
> chore(readme): add contributors

- packages/key-management/README.md
- packages/key-management/package.json
- packages/key-management/src/InMemoryKeyAgent.ts
- packages/key-management/src/KeyAgentBase.ts
- packages/key-management/src/chains/Ethereum/credentialDerivation.ts
- packages/key-management/src/chains/Ethereum/types.ts
- packages/key-management/src/chains/Mina/types.ts
- packages/key-management/src/chains/Starknet/credentialDerivation.ts
- packages/key-management/src/chains/Starknet/keyDerivation.ts
- packages/key-management/src/chains/Starknet/types.ts
- packages/key-management/src/types.ts
- packages/key-management/src/util/bip39.ts
- packages/key-management/test/KeyAgentBase.test.ts
- packages/mina-graphql/src/Providers/types.ts
- packages/mina-wallet/src/Wallet/Wallet.ts
- packages/mina-wallet/src/types.ts
- packages/vault/src/stores.ts
- packages/vault/src/vault.ts
- yarn.lock
- Clean-up and add docs to `key-management` package.
- Spike Starknet key and credential derivation
> chore(`key-management`): clean-up and add docs

- packages/key-management/src/chains/Starknet/credentialDerivation.ts
- packages/key-management/src/chains/Starknet/types.ts
- packages/mina-wallet/src/Wallet/Wallet.ts
add redundant account index to starknet credentials
> fix: add redundant account index to starknet credentials

- CONTRIBUTING.md
- README.md
- qodana.yaml
- Add contributing guidelines
- Update readme
> feat(repo): add contributing.md

- packages/features/src/wallet/hooks/useWallet.ts
- packages/mina-graphql/src/Providers/AccountInfo/AccountInfoProvider.ts
- packages/mina-graphql/src/Providers/ChainHistory/ChainHistoryProvider.ts
- packages/mina-graphql/src/Providers/TxStatus/TxStatusProvider.ts
- packages/mina-graphql/src/Providers/TxSubmit/TxSubmitProvider.ts
- packages/mina-graphql/src/Providers/provider.ts
- packages/mina-graphql/src/Providers/providerArchive.ts
- packages/mina-graphql/src/Providers/types.ts
- packages/mina-wallet/src/Wallet/Wallet.ts
- packages/mina-wallet/src/types.ts
- packages/mina-wallet/test/SwitchNetworks.test.ts
- packages/mina-wallet/test/Wallet.test.ts
- packages/vault/src/index.ts
- packages/vault/src/stores.ts
- packages/vault/src/util.ts
- packages/vault/src/vault.ts
resolves network switching race-conditions
> fix: network switching race-conditions

- apps/extension/index.html
- apps/extension/vite.config.ts
- package.json
- packages/common/src/index.ts
- packages/features/src/common/hooks/useAccount.ts
- packages/features/src/overview/components/AssetList.tsx
- packages/features/src/overview/components/OverviewCard.tsx
- packages/features/src/overview/views/Overview.tsx
- packages/features/src/wallet/hooks/useWallet.ts
- turbo.json
- Refactor balance fetching
- Fix build error associated with OverviewCard
> fix(wallet): reimplement balance fetching

- .github/workflows/apps-extension-ci.yml
- .github/workflows/apps-extension-e2e.yml
- .github/workflows/packages-ui-ci.yml
- apps/extension/package.json
- package.json
- packages/features/src/Router.tsx
- packages/features/src/address-book/components/ContactTile.tsx
- packages/features/src/common/components/BottomNavigation.tsx
- packages/features/src/common/components/MetaField.tsx
- packages/features/src/common/hooks/useAccount.ts
- packages/features/src/common/hooks/useTransaction.ts
- packages/features/src/common/types.ts
- packages/features/src/lock/views/UnlockWallet.tsx
- packages/features/src/overview/components/OverviewCard.tsx
- packages/features/src/receive/views/Receive.tsx
- packages/features/src/settings/views/Settings.tsx
- packages/features/src/staking/views/StakingOverview.tsx
- packages/features/src/transactions/components/TransactionsList.tsx
- packages/features/src/transactions/components/TxIndicator.tsx
- packages/features/src/transactions/components/TxTile.tsx
- packages/features/src/transactions/utils/structurizeTransactions.ts
- packages/features/src/transactions/views/TransactionDetails.tsx
- packages/features/src/transactions/views/Transactions.tsx
- packages/features/src/wallet/hooks/useWallet.ts
- packages/mina-wallet/src/Wallet/Wallet.ts
- packages/ui/src/components/ui/command.tsx
- packages/ui/src/components/ui/toast.tsx
- packages/ui/src/components/ui/toaster.tsx
> chore(transactions): implement new sdk

- apps/extension/e2e/address-book.spec.ts
- apps/extension/e2e/create-wallet.spec.ts
- apps/extension/e2e/restore-wallet.spec.ts
- apps/extension/e2e/unlock-wallet.spec.ts
- packages/features/.ladle/utils.ts
- packages/features/src/address-book/components/NewAddressForm.tsx
- packages/features/src/address-book/views/AddressBook.tsx
- packages/features/src/common/components/BottomNavigation.tsx
- packages/features/src/common/components/CommandMenu.tsx
- packages/features/src/common/components/ViewHeading.tsx
- packages/features/src/lock/views/UnlockWallet.tsx
- packages/features/src/overview/components/OverviewCard.tsx
- Added spec for wallet lock and unlock
- Added spec for adding contact to address book
> chore(e2e): add tests for unlock and address book

- packages/features/src/wallet/hooks/useStores.ts
- packages/features/src/wallet/hooks/useWallet.ts
- packages/mina-wallet/src/Wallet/Wallet.ts
- packages/mina-wallet/src/types.ts
- packages/mina-wallet/test/SwitchNetworks.test.ts
- packages/mina-wallet/test/Wallet/Wallet.test.ts
- packages/vault/README.md
- packages/vault/src/account/accountStore.ts
- packages/vault/src/credentials/credentialsState.ts
- packages/vault/src/credentials/credentialsStore.ts
- packages/vault/src/keyAgent/keyAgentStore.ts
- packages/vault/test/account/accountStore.test.ts
- packages/vault/test/credentials/credentialsStore.test.ts
- packages/web-provider/README.md
- packages/web-provider/package-lock.json
- packages/web-provider/package.json
- packages/web-provider/src/Mina/MinaProvider.ts
- packages/web-provider/src/Mina/MinaWalletWrapper.ts
- packages/web-provider/src/Mina/constants/rpc.ts
- packages/web-provider/src/Mina/index.ts
- packages/web-provider/src/Mina/types.ts
- packages/web-provider/src/index.ts
- packages/web-provider/test/Mina/MinaProvider.test.ts
- packages/web-provider/tsconfig.json
- packages/web-provider/tsup.config.ts
- packages/web-provider/vitest.config.ts
- pnpm-lock.yaml
Pallad needs to be able to connect to zkApps. Introducing a new provider that abstracts over the wallet and receive requests.
> Feat: Web Provider

- packages/mina-core/src/Providers/TxSubmitProvider/types.ts
- packages/mina-graphql/src/Providers/TxSubmit/TxSubmitProvider.ts
- packages/mina-graphql/src/Providers/TxSubmit/mutations.ts
- packages/vault/test/wallet/walletFlow.test.ts
Fixing tx workflow & updating the mutations for submitting transactions.
> fix(tx submission flow, mutations, and interfaces)

- apps/extension/.env.example
- apps/extension/package.json
- packages/features/package.json
- packages/features/src/common/hooks/useAccount.ts
- packages/features/src/common/hooks/useTransaction.ts
- packages/features/src/common/hooks/useTransactions.ts
- packages/features/src/components/list-skeleton.tsx
- packages/features/src/receive/views/Receive.tsx
- packages/features/src/send/components/ConfirmTransactionForm.schema.ts
- packages/features/src/send/components/ConfirmTransactionForm.tsx
- packages/features/src/send/views/TransactionSummary.tsx
- packages/features/src/transactions/views/Transactions.tsx
- packages/key-management/src/InMemoryKeyAgent.ts
- packages/persistence/package.json
- packages/vault/src/keyAgent/keyAgentState.ts
- packages/vault/src/keyAgent/keyAgentStore.ts
- packages/vault/src/vault/vaultState.ts
- packages/vault/src/vault/vaultStore.ts
- packages/vault/test/keyAgent/keyAgentStore.test.ts
- packages/vault/test/wallet/walletFlow.test.ts
- pnpm-lock.yaml
Adding tx sending features to UI.
> chore(update transaction flow in UI)

- packages/features/src/transactions/components/TxIndicator.tsx
- packages/features/src/transactions/components/TxTile.tsx
Improve `getTransactionLabel`  & `TxIndicator` to include delegation transactions.
> Feat: Transaction Labels

- .github/workflows/packages-ci.yml
- packages/mina-graphql/package.json
- packages/mina-graphql/src/Providers/AccountInfo/AccountInfoProvider.ts
- packages/mina-graphql/src/Providers/ChainHistory/ChainHistoryProvider.ts
- packages/mina-graphql/src/Providers/TxStatus/TxStatusProvider.ts
- packages/mina-graphql/src/Providers/TxSubmit/TxSubmitProvider.ts
- packages/mina-graphql/src/Providers/utils/custom-fetch.ts
- packages/mina-graphql/src/Providers/utils/error-policy.ts
- packages/mina-graphql/src/Providers/utils/index.ts
- packages/mina-graphql/src/Providers/utils/json-serializer.ts
- packages/mina-graphql/test/Providers/AccountInfoProvider.test.ts
- packages/mina-graphql/test/Providers/ChainHistoryProvider.test.ts
- packages/mina-graphql/test/Providers/TxStatusProvider.test.ts
- packages/mina-graphql/test/Providers/TxSubmitProvider.test.ts
- packages/mina-graphql/test/provider.test.ts
- packages/mina-graphql/test/providerArchive.test.ts
- packages/mina-graphql/test/unifiedProvider.test.ts
- packages/multi-chain-core/test/Multichain/Provider.test.ts
- pnpm-lock.yaml
This PR introduces advanced GraphQL integration in the Mina providers. It transitions from basic `request` to `GraphQLClient`, enhancing error handling and data serialization.
- **ErrorPolicy**: Allows flexible error handling with modes: `none`, `ignore`,`all`.
- **Custom JSON Serialization**: Implements `defaultJsonSerializer` using `JSONbig`, ensuring precision for large numbers.
- **CustomFetch Function**: Enhances data handling, maintaining integrity of large numerical values and response details.
These improvements enable robust data processing and precision in handling large numbers, optimizing our GraphQL capabilities. It also means that the Mina Providers can all interact with [mina-local-network](https://hub.docker.com/r/o1labs/mina-local-network) in CI!
> Enhanced GraphQL Integration in Mina Provider

- docs/rfc/001-rfc-template.md
- Adds docs dir to repo
- Adds RFCs dir inside the new docs directory
> feat(docs): add rfcs directory

- docs/adr/002-ways-of-working.md
- Adds a new ADR for our ways of working.
> chore(repo): add wow adr

- packages/features/src/common/hooks/use-transaction.ts
- packages/features/src/common/hooks/use-transactions.ts
- packages/features/src/transactions/views/transaction-details.tsx
- packages/vault/src/network-info/default.ts
- packages/vault/test/network-info/network-info-store.test.ts
- Fix details fetching.
- Fix `useTransaction` hook.
> fix(tx): fix tx details fetching

- .github/workflows/pr-reviewer.yml
> chore: add super genius 🤖

- .github/workflows/ai-config/action.yml
- .github/workflows/ai-pr-reviewer.yml
Define config file and path to it so maybe AI can work?
> chore: define ai config action set-up path & file

- packages/features/src/lib/explorer.ts
> fix(tx): fix tx details minaverse links

- apps/extension/src/background/index.ts
- packages/vault/src/objects/objectsStore.ts
- packages/vault/src/vault/vaultState.ts
- packages/vault/src/vault/vaultStore.ts
- packages/vault/test/objects/objectsStore.test.ts
- packages/vault/test/wallet/walletFlow.test.ts
- packages/web-provider/src/mina-network/mina-provider.ts
- packages/web-provider/src/vault-service/types.ts
- packages/web-provider/src/vault-service/vault-service.ts
I believe I have resolved the bug. It turns out the `vaultService` needed to use the rehydrate. I have checked five times manually and no halting of the wallet is happening.
> fix: use rehydrate in vaultService

- packages/features/src/common/hooks/use-account.ts
- packages/features/src/onboarding/routes/mnemonic-confirmation.tsx
- packages/features/src/onboarding/routes/mnemonic-input.tsx
- packages/features/src/overview/components/asset-list.tsx
- packages/features/src/overview/components/overview-card.tsx
- packages/features/src/send/components/confirm-transaction-form.tsx
- packages/features/src/send/components/send-form.tsx
- packages/features/src/send/routes/transaction-summary.tsx
- packages/features/src/staking/views/staking-overview.tsx
- packages/pallad-core/src/Pallad/index.ts
- packages/pallad-core/src/Pallad/utils/fetch-account-properties.ts
- packages/pallad-core/src/Pallad/utils/index.ts
- packages/providers/src/obscura-provider/account-info/account-info-provider.ts
- packages/providers/src/optimism/account-info/account-info-provider.ts
- packages/providers/src/optimism/chain-history/chain-history-provider.ts
- packages/providers/src/optimism/index.ts
- packages/providers/src/optimism/node-status/index.ts
- packages/providers/src/optimism/node-status/node-status-provider.ts
- packages/providers/src/unified-providers/account-info-provider.ts
- packages/providers/src/unified-providers/chain-history-provider.ts
- packages/providers/src/unified-providers/node-status-provider.ts
- packages/providers/src/unified-providers/types.ts
- packages/providers/test/optimism/chain-history/chain-history-provider.test.ts
- packages/vault/src/network-info/default.ts
- packages/vault/src/vault/vaultStore.ts
- packages/vault/test/network-info/network-info-store.test.ts
- packages/web-provider/src/vault-service/vault-service.ts
Adding finishings to Optimism chain-history provider.
> feat: add optimism chain-history provider 🚀

- apps/extension/public/pallad_rpc.js
- apps/extension/src/background/index.ts
- packages/web-provider/src/mina-network/mina-provider.ts
- packages/web-provider/src/web-provider-types/data-model.ts
> Fix: Provider method origins

- packages/features/package.json
- packages/features/src/address-book/views/new-address.tsx
- packages/features/src/components/address-dropdown.tsx
- packages/features/src/components/app-layout.tsx
- packages/features/src/components/autocomplete.tsx
- packages/features/src/components/from-to.tsx
- packages/features/src/components/hash-dropdown.tsx
- packages/features/src/components/menu-bar.tsx
- packages/features/src/components/menu-drawer.tsx
- packages/features/src/lock/views/unlock-wallet.tsx
- packages/features/src/not-found/index.stories.tsx
- packages/features/src/onboarding/index.stories.tsx
- packages/features/src/send/views/transaction-summary.tsx
- packages/features/src/staking/views/staking-overview.tsx
- packages/features/src/transactions/index.stories.tsx
- packages/features/src/transactions/views/transaction-details.tsx
- packages/features/src/wallet/views/overview.tsx
- packages/providers/test/blockberry/stake-pools-provider.test.ts
- pnpm-lock.yaml
> feat(tx details): add dropdowns and tooltips for shortened values

- CONTRIBUTING.md
- README.md
- apps/extension/.env.example
- apps/extension/package.json
- apps/extension/public/pallad_rpc.js
- packages/features/package.json
- packages/features/src/common/assets/placeholder.svg
- packages/features/src/components/menu-drawer.tsx
- packages/features/src/staking/components/block-producer-tile.tsx
- packages/features/src/staking/components/delegate-form.tsx
- packages/features/src/staking/index.stories.tsx
- packages/features/src/staking/routes/block-producers.tsx
- packages/features/src/staking/types.ts
- packages/features/src/staking/views/block-producers.tsx
- packages/providers/test/mina-node/l1-mina-node/individual-providers/account-info-provider.test.ts
- packages/providers/test/mina-node/l1-mina-node/individual-providers/chain-history-provider.test.ts
- packages/providers/test/mina-node/l1-mina-node/individual-providers/node-status-provider.test.ts
- packages/providers/test/mina-node/l1-mina-node/individual-providers/submit-tx-provider.test.ts
- packages/providers/test/unified-providers/individual-providers/account-info-provider.test.ts
- packages/providers/test/unified-providers/unified-provider.test.ts
- packages/vault/src/network-info/default.ts
- pallad_icon.svg
- pnpm-lock.yaml
- Add multi-provider discovery for zkApps
- Implement validators list in Staking
> feat(staking): add validators list

- apps/extension/package.json
- packages/features/package.json
- packages/features/src/error-renderer/views/error.tsx
- packages/features/src/transactions/routes/transactions.tsx
- packages/providers/src/unified-providers/types.ts
- packages/providers/test/unified-providers/individual-providers/chain-history-provider.test.ts
- packages/providers/test/unified-providers/unified-provider.test.ts
- packages/vault/src/network-info/default.ts
- packages/vault/test/network-info/network-info-store.test.ts
> fix(txs): fix pending transactions urls in tx list

- packages/providers/test/unified-providers/unified-provider.test.ts
- packages/providers/test/zeko-scan/chain-history-provider.test.ts
> chore(zeko): skip zeko testnet specs

- packages/features/package.json
> fix(ladle): fix build by falling back to node

- .husky/pre-commit
- apps/extension/package.json
- apps/extension/src/background/handlers/mina-attestations-schemas.ts
- apps/extension/src/sandbox/index.ts
- packages/features/src/web-connector/utils/render-payload.tsx
- packages/web-provider/src/mina-network/mina-provider.ts
this updates the mina-attestations integration to the latest version, 0.5.0
> Fix mina-attestations integration
